Search.appendIndex(
    [
                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters",
            "name": "Characters",
            "summary": "Handle\u0020the\u0020control\u0020characters\u0020used\u0020in\u0020EDI\u0020messages.",
            "url": "classes/Estrato-Edifact-Control-Characters.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AwithControlCharacter\u0028\u0029",
            "name": "withControlCharacter",
            "summary": "Set\u0020a\u0020control\u0020character.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_withControlCharacter"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AwithUNASegment\u0028\u0029",
            "name": "withUNASegment",
            "summary": "Set\u0020whether\u0020the\u0020UNA\u0020segment\u0020should\u0020be\u0020part\u0020of\u0020the\u0020message\u0020or\u0020not.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_withUNASegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AincludesUNASegment\u0028\u0029",
            "name": "includesUNASegment",
            "summary": "Check\u0020whether\u0020the\u0020UNA\u0020segment\u0020should\u0020be\u0020part\u0020of\u0020the\u0020message\u0020or\u0020not.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_includesUNASegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AwithComponentSeparator\u0028\u0029",
            "name": "withComponentSeparator",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020components.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_withComponentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AgetComponentSeparator\u0028\u0029",
            "name": "getComponentSeparator",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020components.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_getComponentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AwithDataSeparator\u0028\u0029",
            "name": "withDataSeparator",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020data\u0020elements.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_withDataSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AgetDataSeparator\u0028\u0029",
            "name": "getDataSeparator",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020data\u0020elements.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_getDataSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AgetSegmentSeparator\u0028\u0029",
            "name": "getSegmentSeparator",
            "summary": "Get\u0020the\u0020character\u0020used\u0020to\u0020separate\u0020segment\u0020tags\u0020from\u0020their\u0020data\u0020components.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_getSegmentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AwithDecimalPoint\u0028\u0029",
            "name": "withDecimalPoint",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020decimal\u0020point.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_withDecimalPoint"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AgetDecimalPoint\u0028\u0029",
            "name": "getDecimalPoint",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020decimal\u0020point.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_getDecimalPoint"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AwithEscapeCharacter\u0028\u0029",
            "name": "withEscapeCharacter",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020an\u0020escape\u0020character.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_withEscapeCharacter"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AgetEscapeCharacter\u0028\u0029",
            "name": "getEscapeCharacter",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020an\u0020escape\u0020character.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_getEscapeCharacter"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AwithSegmentTerminator\u0028\u0029",
            "name": "withSegmentTerminator",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020segment\u0020terminator.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_withSegmentTerminator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AgetSegmentTerminator\u0028\u0029",
            "name": "getSegmentTerminator",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020segment\u0020terminator.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_getSegmentTerminator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AwithReservedSpace\u0028\u0029",
            "name": "withReservedSpace",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020the\u0020reserved\u0020space.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_withReservedSpace"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003AgetReservedSpace\u0028\u0029",
            "name": "getReservedSpace",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020the\u0020reserved\u0020space.",
            "url": "classes/Estrato-Edifact-Control-Characters.html#method_getReservedSpace"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003A\u0024includeUNASegment",
            "name": "includeUNASegment",
            "summary": "",
            "url": "classes/Estrato-Edifact-Control-Characters.html#property_includeUNASegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003A\u0024componentSeparator",
            "name": "componentSeparator",
            "summary": "",
            "url": "classes/Estrato-Edifact-Control-Characters.html#property_componentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003A\u0024dataSeparator",
            "name": "dataSeparator",
            "summary": "",
            "url": "classes/Estrato-Edifact-Control-Characters.html#property_dataSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003A\u0024decimalPoint",
            "name": "decimalPoint",
            "summary": "",
            "url": "classes/Estrato-Edifact-Control-Characters.html#property_decimalPoint"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003A\u0024escapeCharacter",
            "name": "escapeCharacter",
            "summary": "",
            "url": "classes/Estrato-Edifact-Control-Characters.html#property_escapeCharacter"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003A\u0024segmentTerminator",
            "name": "segmentTerminator",
            "summary": "",
            "url": "classes/Estrato-Edifact-Control-Characters.html#property_segmentTerminator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Characters\u003A\u003A\u0024reservedSpace",
            "name": "reservedSpace",
            "summary": "",
            "url": "classes/Estrato-Edifact-Control-Characters.html#property_reservedSpace"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface",
            "name": "CharactersInterface",
            "summary": "Handle\u0020the\u0020control\u0020characters\u0020used\u0020in\u0020EDI\u0020messages.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AwithUNASegment\u0028\u0029",
            "name": "withUNASegment",
            "summary": "Set\u0020whether\u0020the\u0020UNA\u0020segment\u0020should\u0020be\u0020part\u0020of\u0020the\u0020message\u0020or\u0020not.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_withUNASegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AincludesUNASegment\u0028\u0029",
            "name": "includesUNASegment",
            "summary": "Check\u0020whether\u0020the\u0020UNA\u0020segment\u0020should\u0020be\u0020part\u0020of\u0020the\u0020message\u0020or\u0020not.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_includesUNASegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AwithComponentSeparator\u0028\u0029",
            "name": "withComponentSeparator",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020components.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_withComponentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AgetComponentSeparator\u0028\u0029",
            "name": "getComponentSeparator",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020components.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_getComponentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AwithDataSeparator\u0028\u0029",
            "name": "withDataSeparator",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020data\u0020elements.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_withDataSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AgetDataSeparator\u0028\u0029",
            "name": "getDataSeparator",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020data\u0020elements.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_getDataSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AgetSegmentSeparator\u0028\u0029",
            "name": "getSegmentSeparator",
            "summary": "Get\u0020the\u0020character\u0020used\u0020to\u0020separate\u0020segment\u0020tags\u0020from\u0020their\u0020data\u0020components.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_getSegmentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AwithDecimalPoint\u0028\u0029",
            "name": "withDecimalPoint",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020decimal\u0020point.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_withDecimalPoint"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AgetDecimalPoint\u0028\u0029",
            "name": "getDecimalPoint",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020decimal\u0020point.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_getDecimalPoint"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AwithEscapeCharacter\u0028\u0029",
            "name": "withEscapeCharacter",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020an\u0020escape\u0020character.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_withEscapeCharacter"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AgetEscapeCharacter\u0028\u0029",
            "name": "getEscapeCharacter",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020an\u0020escape\u0020character.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_getEscapeCharacter"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AwithSegmentTerminator\u0028\u0029",
            "name": "withSegmentTerminator",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020segment\u0020terminator.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_withSegmentTerminator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AgetSegmentTerminator\u0028\u0029",
            "name": "getSegmentTerminator",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020segment\u0020terminator.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_getSegmentTerminator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AwithReservedSpace\u0028\u0029",
            "name": "withReservedSpace",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020the\u0020reserved\u0020space.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_withReservedSpace"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\CharactersInterface\u003A\u003AgetReservedSpace\u0028\u0029",
            "name": "getReservedSpace",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020the\u0020reserved\u0020space.",
            "url": "classes/Estrato-Edifact-Control-CharactersInterface.html#method_getReservedSpace"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms",
            "name": "Tradacoms",
            "summary": "Handle\u0020the\u0020control\u0020characters\u0020used\u0020in\u0020TRADACOMS\u0020messages.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AwithUNASegment\u0028\u0029",
            "name": "withUNASegment",
            "summary": "Set\u0020whether\u0020the\u0020UNA\u0020segment\u0020should\u0020be\u0020part\u0020of\u0020the\u0020message\u0020or\u0020not.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_withUNASegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AincludesUNASegment\u0028\u0029",
            "name": "includesUNASegment",
            "summary": "Check\u0020whether\u0020the\u0020UNA\u0020segment\u0020should\u0020be\u0020part\u0020of\u0020the\u0020message\u0020or\u0020not.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_includesUNASegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AwithComponentSeparator\u0028\u0029",
            "name": "withComponentSeparator",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020components.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_withComponentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AgetComponentSeparator\u0028\u0029",
            "name": "getComponentSeparator",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020components.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_getComponentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AwithDataSeparator\u0028\u0029",
            "name": "withDataSeparator",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020data\u0020elements.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_withDataSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AgetDataSeparator\u0028\u0029",
            "name": "getDataSeparator",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020to\u0020separate\u0020data\u0020elements.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_getDataSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AgetSegmentSeparator\u0028\u0029",
            "name": "getSegmentSeparator",
            "summary": "Get\u0020the\u0020character\u0020used\u0020to\u0020separate\u0020segment\u0020tags\u0020from\u0020their\u0020data\u0020components.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_getSegmentSeparator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AwithDecimalPoint\u0028\u0029",
            "name": "withDecimalPoint",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020decimal\u0020point.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_withDecimalPoint"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AgetDecimalPoint\u0028\u0029",
            "name": "getDecimalPoint",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020decimal\u0020point.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_getDecimalPoint"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AwithEscapeCharacter\u0028\u0029",
            "name": "withEscapeCharacter",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020an\u0020escape\u0020character.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_withEscapeCharacter"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AgetEscapeCharacter\u0028\u0029",
            "name": "getEscapeCharacter",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020an\u0020escape\u0020character.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_getEscapeCharacter"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AwithSegmentTerminator\u0028\u0029",
            "name": "withSegmentTerminator",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020segment\u0020terminator.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_withSegmentTerminator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AgetSegmentTerminator\u0028\u0029",
            "name": "getSegmentTerminator",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020a\u0020segment\u0020terminator.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_getSegmentTerminator"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AwithReservedSpace\u0028\u0029",
            "name": "withReservedSpace",
            "summary": "Set\u0020the\u0020control\u0020character\u0020used\u0020as\u0020the\u0020reserved\u0020space.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_withReservedSpace"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control\\Tradacoms\u003A\u003AgetReservedSpace\u0028\u0029",
            "name": "getReservedSpace",
            "summary": "Get\u0020the\u0020control\u0020character\u0020used\u0020as\u0020the\u0020reserved\u0020space.",
            "url": "classes/Estrato-Edifact-Control-Tradacoms.html#method_getReservedSpace"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Exceptions\\BadMethodCallException",
            "name": "BadMethodCallException",
            "summary": "",
            "url": "classes/Estrato-Edifact-Exceptions-BadMethodCallException.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Exceptions\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Estrato-Edifact-Exceptions-Exception.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Exceptions\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/Estrato-Edifact-Exceptions-InvalidArgumentException.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Exceptions\\ParseException",
            "name": "ParseException",
            "summary": "",
            "url": "classes/Estrato-Edifact-Exceptions-ParseException.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message",
            "name": "Message",
            "summary": "Represent\u0020an\u0020EDI\u0020message\u0020for\u0020both\u0020reading\u0020and\u0020writing.",
            "url": "classes/Estrato-Edifact-Message.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003AfromFile\u0028\u0029",
            "name": "fromFile",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020from\u0020a\u0020file.",
            "url": "classes/Estrato-Edifact-Message.html#method_fromFile"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003AfromString\u0028\u0029",
            "name": "fromString",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020from\u0020a\u0020string.",
            "url": "classes/Estrato-Edifact-Message.html#method_fromString"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003AfromSegments\u0028\u0029",
            "name": "fromSegments",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020from\u0020an\u0020array\u0020of\u0020segments.",
            "url": "classes/Estrato-Edifact-Message.html#method_fromSegments"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003AgetAllSegments\u0028\u0029",
            "name": "getAllSegments",
            "summary": "Get\u0020all\u0020the\u0020segments.",
            "url": "classes/Estrato-Edifact-Message.html#method_getAllSegments"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003AgetSegments\u0028\u0029",
            "name": "getSegments",
            "summary": "Get\u0020all\u0020the\u0020segments\u0020that\u0020match\u0020the\u0020requested\u0020code.",
            "url": "classes/Estrato-Edifact-Message.html#method_getSegments"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003AgetSegment\u0028\u0029",
            "name": "getSegment",
            "summary": "Get\u0020the\u0020first\u0020segment\u0020that\u0020matches\u0020the\u0020requested\u0020code.",
            "url": "classes/Estrato-Edifact-Message.html#method_getSegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003AaddSegments\u0028\u0029",
            "name": "addSegments",
            "summary": "Add\u0020multiple\u0020segments\u0020to\u0020the\u0020message.",
            "url": "classes/Estrato-Edifact-Message.html#method_addSegments"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003AaddSegment\u0028\u0029",
            "name": "addSegment",
            "summary": "Add\u0020a\u0020segment\u0020to\u0020the\u0020message.",
            "url": "classes/Estrato-Edifact-Message.html#method_addSegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Serialize\u0020all\u0020the\u0020segments\u0020added\u0020to\u0020this\u0020object.",
            "url": "classes/Estrato-Edifact-Message.html#method_serialize"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Allow\u0020the\u0020object\u0020to\u0020be\u0020serialized\u0020by\u0020casting\u0020to\u0020a\u0020string.",
            "url": "classes/Estrato-Edifact-Message.html#method___toString"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Message\u003A\u003A\u0024segments",
            "name": "segments",
            "summary": "",
            "url": "classes/Estrato-Edifact-Message.html#property_segments"
        },                {
            "fqsen": "\\Estrato\\Edifact\\MessageInterface",
            "name": "MessageInterface",
            "summary": "",
            "url": "classes/Estrato-Edifact-MessageInterface.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\MessageInterface\u003A\u003AgetAllSegments\u0028\u0029",
            "name": "getAllSegments",
            "summary": "Get\u0020all\u0020the\u0020segments.",
            "url": "classes/Estrato-Edifact-MessageInterface.html#method_getAllSegments"
        },                {
            "fqsen": "\\Estrato\\Edifact\\MessageInterface\u003A\u003AgetSegments\u0028\u0029",
            "name": "getSegments",
            "summary": "Get\u0020all\u0020the\u0020segments\u0020that\u0020match\u0020the\u0020requested\u0020code.",
            "url": "classes/Estrato-Edifact-MessageInterface.html#method_getSegments"
        },                {
            "fqsen": "\\Estrato\\Edifact\\MessageInterface\u003A\u003AgetSegment\u0028\u0029",
            "name": "getSegment",
            "summary": "Get\u0020the\u0020first\u0020segment\u0020that\u0020matches\u0020the\u0020requested\u0020code.",
            "url": "classes/Estrato-Edifact-MessageInterface.html#method_getSegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\MessageInterface\u003A\u003AaddSegments\u0028\u0029",
            "name": "addSegments",
            "summary": "Add\u0020multiple\u0020segments\u0020to\u0020the\u0020message.",
            "url": "classes/Estrato-Edifact-MessageInterface.html#method_addSegments"
        },                {
            "fqsen": "\\Estrato\\Edifact\\MessageInterface\u003A\u003AaddSegment\u0028\u0029",
            "name": "addSegment",
            "summary": "Add\u0020a\u0020segment\u0020to\u0020the\u0020message.",
            "url": "classes/Estrato-Edifact-MessageInterface.html#method_addSegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\MessageInterface\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Serialize\u0020all\u0020the\u0020segments\u0020added\u0020to\u0020this\u0020object.",
            "url": "classes/Estrato-Edifact-MessageInterface.html#method_serialize"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Parser",
            "name": "Parser",
            "summary": "Parse\u0020EDI\u0020messages\u0020into\u0020an\u0020array\u0020of\u0020segments.",
            "url": "classes/Estrato-Edifact-Parser.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020instance.",
            "url": "classes/Estrato-Edifact-Parser.html#method___construct"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parse\u0020the\u0020message\u0020into\u0020an\u0020array\u0020of\u0020segments.",
            "url": "classes/Estrato-Edifact-Parser.html#method_parse"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Parser\u003A\u003AgetControlCharacters\u0028\u0029",
            "name": "getControlCharacters",
            "summary": "Read\u0020\u0028and\u0020remove\u0029\u0020the\u0020UNA\u0020segment\u0020from\u0020the\u0020passed\u0020string.",
            "url": "classes/Estrato-Edifact-Parser.html#method_getControlCharacters"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Parser\u003A\u003AconvertTokensToSegments\u0028\u0029",
            "name": "convertTokensToSegments",
            "summary": "Convert\u0020the\u0020tokenized\u0020message\u0020into\u0020an\u0020array\u0020of\u0020segments.",
            "url": "classes/Estrato-Edifact-Parser.html#method_convertTokensToSegments"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Parser\u003A\u003AproduceSegment\u0028\u0029",
            "name": "produceSegment",
            "summary": "",
            "url": "classes/Estrato-Edifact-Parser.html#method_produceSegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Parser\u003A\u003A\u0024factory",
            "name": "factory",
            "summary": "",
            "url": "classes/Estrato-Edifact-Parser.html#property_factory"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Parser\u003A\u003A\u0024tokenizer",
            "name": "tokenizer",
            "summary": "",
            "url": "classes/Estrato-Edifact-Parser.html#property_tokenizer"
        },                {
            "fqsen": "\\Estrato\\Edifact\\ParserInterface",
            "name": "ParserInterface",
            "summary": "",
            "url": "classes/Estrato-Edifact-ParserInterface.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\ParserInterface\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parse\u0020the\u0020message\u0020into\u0020an\u0020array\u0020of\u0020segments.",
            "url": "classes/Estrato-Edifact-ParserInterface.html#method_parse"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\AbstractSegment",
            "name": "AbstractSegment",
            "summary": "Represent\u0020a\u0020segment\u0020of\u0020an\u0020EDI\u0020message.",
            "url": "classes/Estrato-Edifact-Segments-AbstractSegment.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\AbstractSegment\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020instance.",
            "url": "classes/Estrato-Edifact-Segments-AbstractSegment.html#method___construct"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\AbstractSegment\u003A\u003AgetSegmentCode\u0028\u0029",
            "name": "getSegmentCode",
            "summary": "Get\u0020the\u0020code\u0020of\u0020this\u0020segment.",
            "url": "classes/Estrato-Edifact-Segments-AbstractSegment.html#method_getSegmentCode"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\AbstractSegment\u003A\u003AgetAllElements\u0028\u0029",
            "name": "getAllElements",
            "summary": "Get\u0020all\u0020the\u0020elements\u0020from\u0020the\u0020segment.",
            "url": "classes/Estrato-Edifact-Segments-AbstractSegment.html#method_getAllElements"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\AbstractSegment\u003A\u003AgetElement\u0028\u0029",
            "name": "getElement",
            "summary": "Get\u0020an\u0020element\u0020from\u0020the\u0020segment.",
            "url": "classes/Estrato-Edifact-Segments-AbstractSegment.html#method_getElement"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\AbstractSegment\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/Estrato-Edifact-Segments-AbstractSegment.html#property_code"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\AbstractSegment\u003A\u003A\u0024elements",
            "name": "elements",
            "summary": "",
            "url": "classes/Estrato-Edifact-Segments-AbstractSegment.html#property_elements"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\Factory",
            "name": "Factory",
            "summary": "Factory\u0020for\u0020producing\u0020segments.",
            "url": "classes/Estrato-Edifact-Segments-Factory.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\Factory\u003A\u003AcreateSegment\u0028\u0029",
            "name": "createSegment",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020of\u0020the\u0020relevant\u0020class\u0020type.",
            "url": "classes/Estrato-Edifact-Segments-Factory.html#method_createSegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\FactoryInterface",
            "name": "FactoryInterface",
            "summary": "Factory\u0020for\u0020producing\u0020segments.",
            "url": "classes/Estrato-Edifact-Segments-FactoryInterface.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\FactoryInterface\u003A\u003AcreateSegment\u0028\u0029",
            "name": "createSegment",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020of\u0020the\u0020relevant\u0020class\u0020type.",
            "url": "classes/Estrato-Edifact-Segments-FactoryInterface.html#method_createSegment"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\Segment",
            "name": "Segment",
            "summary": "Represent\u0020a\u0020segment\u0020of\u0020an\u0020EDI\u0020message.",
            "url": "classes/Estrato-Edifact-Segments-Segment.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\SegmentInterface",
            "name": "SegmentInterface",
            "summary": "Represent\u0020a\u0020segment\u0020of\u0020an\u0020EDI\u0020message.",
            "url": "classes/Estrato-Edifact-Segments-SegmentInterface.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\SegmentInterface\u003A\u003AgetSegmentCode\u0028\u0029",
            "name": "getSegmentCode",
            "summary": "Get\u0020the\u0020code\u0020of\u0020this\u0020segment.",
            "url": "classes/Estrato-Edifact-Segments-SegmentInterface.html#method_getSegmentCode"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\SegmentInterface\u003A\u003AgetAllElements\u0028\u0029",
            "name": "getAllElements",
            "summary": "Get\u0020all\u0020the\u0020elements\u0020from\u0020the\u0020segment.",
            "url": "classes/Estrato-Edifact-Segments-SegmentInterface.html#method_getAllElements"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments\\SegmentInterface\u003A\u003AgetElement\u0028\u0029",
            "name": "getElement",
            "summary": "Get\u0020an\u0020element\u0020from\u0020the\u0020segment.",
            "url": "classes/Estrato-Edifact-Segments-SegmentInterface.html#method_getElement"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Serializer",
            "name": "Serializer",
            "summary": "Serialize\u0020a\u0020bunch\u0020of\u0020segments\u0020into\u0020an\u0020EDI\u0020message\u0020string.",
            "url": "classes/Estrato-Edifact-Serializer.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Serializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Estrato-Edifact-Serializer.html#method___construct"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Serializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Serialize\u0020all\u0020the\u0020passed\u0020segments.",
            "url": "classes/Estrato-Edifact-Serializer.html#method_serialize"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Serializer\u003A\u003Aescape\u0028\u0029",
            "name": "escape",
            "summary": "Escapes\u0020control\u0020characters.",
            "url": "classes/Estrato-Edifact-Serializer.html#method_escape"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Serializer\u003A\u003A\u0024characters",
            "name": "characters",
            "summary": "",
            "url": "classes/Estrato-Edifact-Serializer.html#property_characters"
        },                {
            "fqsen": "\\Estrato\\Edifact\\SerializerInterface",
            "name": "SerializerInterface",
            "summary": "",
            "url": "classes/Estrato-Edifact-SerializerInterface.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\SerializerInterface\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Serialize\u0020all\u0020the\u0020passed\u0020segments.",
            "url": "classes/Estrato-Edifact-SerializerInterface.html#method_serialize"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Token",
            "name": "Token",
            "summary": "",
            "url": "classes/Estrato-Edifact-Token.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Token\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Estrato-Edifact-Token.html#method___construct"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Token\u003A\u003ACONTENT",
            "name": "CONTENT",
            "summary": "",
            "url": "classes/Estrato-Edifact-Token.html#constant_CONTENT"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Token\u003A\u003ACOMPONENT_SEPARATOR",
            "name": "COMPONENT_SEPARATOR",
            "summary": "",
            "url": "classes/Estrato-Edifact-Token.html#constant_COMPONENT_SEPARATOR"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Token\u003A\u003ADATA_SEPARATOR",
            "name": "DATA_SEPARATOR",
            "summary": "",
            "url": "classes/Estrato-Edifact-Token.html#constant_DATA_SEPARATOR"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Token\u003A\u003ATERMINATOR",
            "name": "TERMINATOR",
            "summary": "",
            "url": "classes/Estrato-Edifact-Token.html#constant_TERMINATOR"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Token\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Estrato-Edifact-Token.html#property_type"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Token\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Estrato-Edifact-Token.html#property_value"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer",
            "name": "Tokenizer",
            "summary": "Convert\u0020EDI\u0020messages\u0020into\u0020tokens\u0020for\u0020parsing.",
            "url": "classes/Estrato-Edifact-Tokenizer.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003AgetTokens\u0028\u0029",
            "name": "getTokens",
            "summary": "Convert\u0020the\u0020passed\u0020message\u0020into\u0020tokens.",
            "url": "classes/Estrato-Edifact-Tokenizer.html#method_getTokens"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003AreadNextChar\u0028\u0029",
            "name": "readNextChar",
            "summary": "Read\u0020the\u0020next\u0020character\u0020from\u0020the\u0020message.",
            "url": "classes/Estrato-Edifact-Tokenizer.html#method_readNextChar"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003AgetNextChar\u0028\u0029",
            "name": "getNextChar",
            "summary": "Get\u0020the\u0020next\u0020character\u0020from\u0020the\u0020message.",
            "url": "classes/Estrato-Edifact-Tokenizer.html#method_getNextChar"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003AgetNextToken\u0028\u0029",
            "name": "getNextToken",
            "summary": "Get\u0020the\u0020next\u0020token\u0020from\u0020the\u0020message.",
            "url": "classes/Estrato-Edifact-Tokenizer.html#method_getNextToken"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003AisControlCharacter\u0028\u0029",
            "name": "isControlCharacter",
            "summary": "Check\u0020if\u0020the\u0020current\u0020character\u0020is\u0020a\u0020control\u0020character.",
            "url": "classes/Estrato-Edifact-Tokenizer.html#method_isControlCharacter"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003AstoreCurrentCharAndReadNext\u0028\u0029",
            "name": "storeCurrentCharAndReadNext",
            "summary": "Store\u0020the\u0020current\u0020character\u0020and\u0020read\u0020the\u0020next\u0020one\u0020from\u0020the\u0020message.",
            "url": "classes/Estrato-Edifact-Tokenizer.html#method_storeCurrentCharAndReadNext"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003AextractStoredChars\u0028\u0029",
            "name": "extractStoredChars",
            "summary": "Get\u0020the\u0020previously\u0020stored\u0020characters.",
            "url": "classes/Estrato-Edifact-Tokenizer.html#method_extractStoredChars"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003AendOfMessage\u0028\u0029",
            "name": "endOfMessage",
            "summary": "Check\u0020if\u0020we\u0027ve\u0020reached\u0020the\u0020end\u0020of\u0020the\u0020message",
            "url": "classes/Estrato-Edifact-Tokenizer.html#method_endOfMessage"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/Estrato-Edifact-Tokenizer.html#property_message"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003A\u0024position",
            "name": "position",
            "summary": "",
            "url": "classes/Estrato-Edifact-Tokenizer.html#property_position"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003A\u0024characters",
            "name": "characters",
            "summary": "",
            "url": "classes/Estrato-Edifact-Tokenizer.html#property_characters"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003A\u0024char",
            "name": "char",
            "summary": "",
            "url": "classes/Estrato-Edifact-Tokenizer.html#property_char"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003A\u0024string",
            "name": "string",
            "summary": "",
            "url": "classes/Estrato-Edifact-Tokenizer.html#property_string"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Tokenizer\u003A\u003A\u0024isEscaped",
            "name": "isEscaped",
            "summary": "",
            "url": "classes/Estrato-Edifact-Tokenizer.html#property_isEscaped"
        },                {
            "fqsen": "\\Estrato\\Edifact\\TokenizerInterface",
            "name": "TokenizerInterface",
            "summary": "Convert\u0020EDI\u0020messages\u0020into\u0020tokens\u0020for\u0020parsing.",
            "url": "classes/Estrato-Edifact-TokenizerInterface.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\TokenizerInterface\u003A\u003AgetTokens\u0028\u0029",
            "name": "getTokens",
            "summary": "Convert\u0020the\u0020passed\u0020message\u0020into\u0020tokens.",
            "url": "classes/Estrato-Edifact-TokenizerInterface.html#method_getTokens"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\Control\\CharactersTest",
            "name": "CharactersTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-Control-CharactersTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\Control\\CharactersTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-Control-CharactersTest.html#method_setUp"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\Control\\CharactersTest\u003A\u003AtestInvalidControlCharacter1\u0028\u0029",
            "name": "testInvalidControlCharacter1",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-Control-CharactersTest.html#method_testInvalidControlCharacter1"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\Control\\CharactersTest\u003A\u003AtestInvalidControlCharacter2\u0028\u0029",
            "name": "testInvalidControlCharacter2",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-Control-CharactersTest.html#method_testInvalidControlCharacter2"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\Control\\CharactersTest\u003A\u003A\u0024characters",
            "name": "characters",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-Control-CharactersTest.html#property_characters"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ExceptionTest",
            "name": "ExceptionTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ExceptionTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ExceptionTest\u003A\u003AexceptionProvider\u0028\u0029",
            "name": "exceptionProvider",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ExceptionTest.html#method_exceptionProvider"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ExceptionTest\u003A\u003AtestExceptionInterface\u0028\u0029",
            "name": "testExceptionInterface",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ExceptionTest.html#method_testExceptionInterface"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\InAndOutTest",
            "name": "InAndOutTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-InAndOutTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\InAndOutTest\u003A\u003AmessageProvider\u0028\u0029",
            "name": "messageProvider",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-InAndOutTest.html#method_messageProvider"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\InAndOutTest\u003A\u003AtestFormat\u0028\u0029",
            "name": "testFormat",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-InAndOutTest.html#method_testFormat"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\InAndOutTest\u003A\u003AtestTradacoms1\u0028\u0029",
            "name": "testTradacoms1",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-InAndOutTest.html#method_testTradacoms1"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\MessageTest",
            "name": "MessageTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-MessageTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\MessageTest\u003A\u003AtestFromFile\u0028\u0029",
            "name": "testFromFile",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-MessageTest.html#method_testFromFile"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\MessageTest\u003A\u003AtestCreateWithSegments\u0028\u0029",
            "name": "testCreateWithSegments",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-MessageTest.html#method_testCreateWithSegments"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\MessageTest\u003A\u003AtestGetSegments\u0028\u0029",
            "name": "testGetSegments",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-MessageTest.html#method_testGetSegments"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\MessageTest\u003A\u003AtestGetSegmentsDoesntExist\u0028\u0029",
            "name": "testGetSegmentsDoesntExist",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-MessageTest.html#method_testGetSegmentsDoesntExist"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\MessageTest\u003A\u003AtestGetSegment\u0028\u0029",
            "name": "testGetSegment",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-MessageTest.html#method_testGetSegment"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\MessageTest\u003A\u003AtestGetSegmentDoesntExist\u0028\u0029",
            "name": "testGetSegmentDoesntExist",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-MessageTest.html#method_testGetSegmentDoesntExist"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest",
            "name": "ParserTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_setUp"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AgetControlCharacters\u0028\u0029",
            "name": "getControlCharacters",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_getControlCharacters"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestGetControlCharacters1\u0028\u0029",
            "name": "testGetControlCharacters1",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testGetControlCharacters1"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestGetControlCharacters2\u0028\u0029",
            "name": "testGetControlCharacters2",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testGetControlCharacters2"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestGetControlCharacters3\u0028\u0029",
            "name": "testGetControlCharacters3",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testGetControlCharacters3"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestGetControlCharacters4\u0028\u0029",
            "name": "testGetControlCharacters4",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testGetControlCharacters4"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestGetControlCharacters5\u0028\u0029",
            "name": "testGetControlCharacters5",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testGetControlCharacters5"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AassertSegments\u0028\u0029",
            "name": "assertSegments",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_assertSegments"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestBasic1\u0028\u0029",
            "name": "testBasic1",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testBasic1"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestBasic2\u0028\u0029",
            "name": "testBasic2",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testBasic2"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestEscapeCharacter\u0028\u0029",
            "name": "testEscapeCharacter",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testEscapeCharacter"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestEscapeComponentSeparator\u0028\u0029",
            "name": "testEscapeComponentSeparator",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testEscapeComponentSeparator"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestEscapeDataSeparator\u0028\u0029",
            "name": "testEscapeDataSeparator",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testEscapeDataSeparator"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestEscapeDecimalPoint\u0028\u0029",
            "name": "testEscapeDecimalPoint",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testEscapeDecimalPoint"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestEscapeSegmentTerminator\u0028\u0029",
            "name": "testEscapeSegmentTerminator",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testEscapeSegmentTerminator"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestEscapeSequence\u0028\u0029",
            "name": "testEscapeSequence",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testEscapeSequence"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestInvalid1\u0028\u0029",
            "name": "testInvalid1",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testInvalid1"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003AtestCustomTokenizer\u0028\u0029",
            "name": "testCustomTokenizer",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#method_testCustomTokenizer"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\ParserTest\u003A\u003A\u0024parser",
            "name": "parser",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-ParserTest.html#property_parser"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\PerformanceTest",
            "name": "PerformanceTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-PerformanceTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\PerformanceTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-PerformanceTest.html#method_setUp"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\PerformanceTest\u003A\u003AtearDown\u0028\u0029",
            "name": "tearDown",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-PerformanceTest.html#method_tearDown"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\PerformanceTest\u003A\u003AtestTokenizerPerformance\u0028\u0029",
            "name": "testTokenizerPerformance",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-PerformanceTest.html#method_testTokenizerPerformance"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\PerformanceTest\u003A\u003A\u0024tmp",
            "name": "tmp",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-PerformanceTest.html#property_tmp"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SegmentTest",
            "name": "SegmentTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SegmentTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SegmentTest\u003A\u003AtestGetSegmentCode\u0028\u0029",
            "name": "testGetSegmentCode",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SegmentTest.html#method_testGetSegmentCode"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SegmentTest\u003A\u003AtestGetAllElements\u0028\u0029",
            "name": "testGetAllElements",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SegmentTest.html#method_testGetAllElements"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SegmentTest\u003A\u003AtestGetElement1\u0028\u0029",
            "name": "testGetElement1",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SegmentTest.html#method_testGetElement1"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SegmentTest\u003A\u003AtestGetElement2\u0028\u0029",
            "name": "testGetElement2",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SegmentTest.html#method_testGetElement2"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SegmentTest\u003A\u003AtestGetElement3\u0028\u0029",
            "name": "testGetElement3",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SegmentTest.html#method_testGetElement3"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest",
            "name": "SerializerTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_setUp"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AassertSegments\u0028\u0029",
            "name": "assertSegments",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_assertSegments"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestBasic1\u0028\u0029",
            "name": "testBasic1",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testBasic1"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestBasic2\u0028\u0029",
            "name": "testBasic2",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testBasic2"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestBasic3\u0028\u0029",
            "name": "testBasic3",
            "summary": "Ensure\u0020we\u0020can\u0020handle\u0020null\u0020values.",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testBasic3"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestSerialize1\u0028\u0029",
            "name": "testSerialize1",
            "summary": "Ensure\u0020we\u0020can\u0020produce\u0020a\u0020file\u0020without\u0020a\u0020UNA\u0020segment.",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testSerialize1"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestEscapeCharacter\u0028\u0029",
            "name": "testEscapeCharacter",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testEscapeCharacter"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestEscapeComponentSeparator\u0028\u0029",
            "name": "testEscapeComponentSeparator",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testEscapeComponentSeparator"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestEscapeDataSeparator\u0028\u0029",
            "name": "testEscapeDataSeparator",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testEscapeDataSeparator"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestEscapeDecimalPoint\u0028\u0029",
            "name": "testEscapeDecimalPoint",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testEscapeDecimalPoint"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestEscapeSegmentTerminator\u0028\u0029",
            "name": "testEscapeSegmentTerminator",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testEscapeSegmentTerminator"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestReservedSpace\u0028\u0029",
            "name": "testReservedSpace",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testReservedSpace"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003AtestEscapeSequence\u0028\u0029",
            "name": "testEscapeSequence",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#method_testEscapeSequence"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\SerializerTest\u003A\u003A\u0024serializer",
            "name": "serializer",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-SerializerTest.html#property_serializer"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest",
            "name": "TokenizerTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_setUp"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AassertTokens\u0028\u0029",
            "name": "assertTokens",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_assertTokens"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AtestBasic\u0028\u0029",
            "name": "testBasic",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_testBasic"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AtestMultiple\u0028\u0029",
            "name": "testMultiple",
            "summary": "Regression\u0020test\u0020for\u0020https\u003A\/\/github.com\/estratocloud\/edifact\/issues\/14",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_testMultiple"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AtestEscape\u0028\u0029",
            "name": "testEscape",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_testEscape"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AtestDoubleEscape\u0028\u0029",
            "name": "testDoubleEscape",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_testDoubleEscape"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AtestTripleEscape\u0028\u0029",
            "name": "testTripleEscape",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_testTripleEscape"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AtestQuadrupleEscape\u0028\u0029",
            "name": "testQuadrupleEscape",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_testQuadrupleEscape"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AtestIgnoreWhitespace\u0028\u0029",
            "name": "testIgnoreWhitespace",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_testIgnoreWhitespace"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003AtestNoTerminator\u0028\u0029",
            "name": "testNoTerminator",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#method_testNoTerminator"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenizerTest\u003A\u003A\u0024tokenizer",
            "name": "tokenizer",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenizerTest.html#property_tokenizer"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenTest",
            "name": "TokenTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenTest\u003A\u003AtestType\u0028\u0029",
            "name": "testType",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenTest.html#method_testType"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TokenTest\u003A\u003AtestValue\u0028\u0029",
            "name": "testValue",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TokenTest.html#method_testValue"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TradacomsTest",
            "name": "TradacomsTest",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TradacomsTest.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\TradacomsTest\u003A\u003AtestTradacoms1\u0028\u0029",
            "name": "testTradacoms1",
            "summary": "",
            "url": "classes/Estrato-EdifactTests-TradacomsTest.html#method_testTradacoms1"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Control",
            "name": "Control",
            "summary": "",
            "url": "namespaces/estrato-edifact-control.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/estrato-edifact-exceptions.html"
        },                {
            "fqsen": "\\Estrato\\Edifact",
            "name": "Edifact",
            "summary": "",
            "url": "namespaces/estrato-edifact.html"
        },                {
            "fqsen": "\\Estrato",
            "name": "Estrato",
            "summary": "",
            "url": "namespaces/estrato.html"
        },                {
            "fqsen": "\\Estrato\\Edifact\\Segments",
            "name": "Segments",
            "summary": "",
            "url": "namespaces/estrato-edifact-segments.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests\\Control",
            "name": "Control",
            "summary": "",
            "url": "namespaces/estrato-edifacttests-control.html"
        },                {
            "fqsen": "\\Estrato\\EdifactTests",
            "name": "EdifactTests",
            "summary": "",
            "url": "namespaces/estrato-edifacttests.html"
        }            ]
);
